name: stash_dio
version: 1.0.0-dev.1
description: >-
  Dio extension for the stash caching API. Provides an interceptor that uses
  Stash as a caching layer for Dio
homepage: https://github.com/ivoleitao/stash_dio

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  http_parser: ^3.1.4
  crypto: ^2.1.4
  dio: ^3.0.9
  stash:
    path: ../stash

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.3
  test_coverage: ^0.4.1
  build_runner: ^1.10.0
  build_verify: ^1.1.1
  json_serializable: ^3.3.0
  mockito: ^4.1.1
