name: stash_dio
version: 2.0.0-nullsafety.1
description: >-
  Dio extension for the stash caching API. Provides an interceptor that uses
  Stash as a caching layer for Dio
homepage: https://github.com/ivoleitao/stash_dio

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  equatable: ^2.0.0-nullsafety.4
  http_parser: ^4.0.0
  crypto: ^3.0.0
  dio: ^4.0.0-beta7
  stash: ^2.0.0-nullsafety.2
  #stash:
  #  path: ../stash

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4
    # test_coverage: ^0.4.3
  mocktail: ^0.0.1-dev.11
