name: stash_dio
version: 1.0.2
description: >-
  Dio extension for the stash caching API. Provides an interceptor that uses
  Stash as a caching layer for Dio
homepage: https://github.com/ivoleitao/stash_dio

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  http_parser: ^3.1.4
  crypto: ^2.1.5
  dio: ^3.0.10
  stash: ^1.0.2
  #stash:
  #  path: ../stash

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
  test_coverage: ^0.4.3
  mockito: ^4.1.2
